### ISSUE TITLE
gl_example.py is not working on linux

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/pyopenxr#55]
It doesn't crash, but it's not displaying the colors in each eye. At least not for me with Ubuntu LTS and og HTC Vive.

**Comment by nlsdvl** [comment]
I don't have a Vive to try, but it works fine for me with the monado runtime on Ubuntu 20.04 LTS. 
As a side note, I also get it to work with Quest2 on windows.

**Comment by el-dee** [comment]
The problem is this one https://github.com/ValveSoftware/SteamVR-for-Linux/issues/421 (and as of SteamVR 1.21.8 not yet solved)

Christoph Haag made a layer to work around this problem, see https://github.com/ChristophHaag/gl_context_fix_layer

When using this layer with `gl_example.py` there is some improvement: I get the blue color for the right eye, but the left eye stays black, however now if I activate the mirror window I correctly have the left side of the window colored green and the right side colored blue.
