### ISSUE TITLE
Error when running pyopenx

### ISSUE THREAD

**Issue by msolive1985** [cmbruns/pyopenxr#85]
OS: Windows
Issue: api_version=api_version.number() -> TypeError: an integer is required (got type Version)

Hi, 

I am trying to use it to track my Meta Quest 2 Controllers, but I have this error. I am looking forward to hearing from you. Thank you.

**Comment by cmbruns** [comment]
It looks like this might be related to using python version 3.6 or maybe 3.7. I've been using python 3.8 and 3.9 in development.
https://github.com/cmbruns/pyopenxr/actions/runs/2641869182

**Comment by msolive1985** [comment]
Thank you for your reply. Yes, the python version I used is python 3.7. I will update it to 3.9. I will keep it posted.

**Comment by cmbruns** [comment]
Thank you. I'm glad you are working with the Quest 2 because that's an important system and I do not recall anyone else mentioning using it with pyopenxr yet. So I am eager to learn more about your experience; good or bad.

I will likely restore compatibility with python 3.6, 3.7, and 3.10 in the next release. But it might take me a week to get that together.
